
x = 0
assert x == 1, 'Произошла ошибка!'
#raise Exception('error')
